services:

  nginx:
    depends_on:
      - wordpress
    container_name: nginx
    build: requirements/nginx/
    image: nginx
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - jbortolo_network
    ports:
      - "443:443"
    restart: always


  mariadb:
    container_name: mariadb
    build: requirements/mariadb
    image: mariadb
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - jbortolo_network
    env_file:
      - .env
    restart: always
  
  wordpress:
    depends_on:
      - mariadb
    container_name: wordpress
    build: requirements/wordpress
    image: wordpress
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - jbortolo_network
    env_file:
      - .env
    restart: always

volumes:

  wordpress_data:
    driver: local
    driver_opts:
      device: "/home/${USER}/data/wordpress"
      o: bind
      type: none
  
  mariadb_data:
    driver: local
    driver_opts:
      device: "/home/${USER}/data/mariadb"
      o: bind
      type: none


networks:
  jbortolo_network:
    name: jbortolo_network
    driver: bridge